### ISSUE TITLE
[BUG] Edit Page Lighthouse Fixes

### ISSUE THREAD

**Issue by christoff-linde** [IMY772-2022/via-web#113]
- Card sized bigger than the viewport

[Lighthouse Report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1656152522042-14752.report.html)

**Comment by brian-david** [comment]
Will check this out tomorrow ☝️

**Comment by christoff-linde** [comment]
@brian-david how far are you with this? We need to get this stuff done asap
